import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Linktree Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 h-screen">
      <div className="flex flex-col items-center justify-center">{children}</div>
      <div className="bg-cyan-200 w-full" />
    </div>
  );
}
